# Generated by Django 3.0.5 on 2020-04-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_nomber',
            new_name='phone_number',
        ),
    ]
